### ISSUE TITLE
`bosh-lint manifest` should fail if /instance_groups/name=foo/vm_type missing

### ISSUE THREAD

**Issue by drnic** [bosh-tools/bosh-ext-cli#12]
Same for stemcell. The following are required by bosh, but lint doesn't complain.

```yaml
  vm_type: default
  stemcell: default
  networks: [{name: default}]
```
