### ISSUE TITLE
bosh lint should warn about nested properties in spec files

### ISSUE THREAD

**Issue by tjvman** [bosh-tools/bosh-ext-cli#17]
if my `fakejob/spec` looks like this:
```
---
name: fakejob
packages: []
properties:
  foo: 
    bar:
      description: 'it is bar'
```
should result in a warning that property nesting is not allowed
